
package ws1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NumberImplService", targetNamespace = "http://WS_Number/", wsdlLocation = "http://localhost:8888/NumberService/Numbers?wsdl")
public class NumberImplService
    extends Service
{

    private final static URL NUMBERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException NUMBERIMPLSERVICE_EXCEPTION;
    private final static QName NUMBERIMPLSERVICE_QNAME = new QName("http://WS_Number/", "NumberImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/NumberService/Numbers?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NUMBERIMPLSERVICE_WSDL_LOCATION = url;
        NUMBERIMPLSERVICE_EXCEPTION = e;
    }

    public NumberImplService() {
        super(__getWsdlLocation(), NUMBERIMPLSERVICE_QNAME);
    }

    public NumberImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NUMBERIMPLSERVICE_QNAME, features);
    }

    public NumberImplService(URL wsdlLocation) {
        super(wsdlLocation, NUMBERIMPLSERVICE_QNAME);
    }

    public NumberImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NUMBERIMPLSERVICE_QNAME, features);
    }

    public NumberImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NumberImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Numbers
     */
    @WebEndpoint(name = "NumberImplPort")
    public Numbers getNumberImplPort() {
        return super.getPort(new QName("http://WS_Number/", "NumberImplPort"), Numbers.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Numbers
     */
    @WebEndpoint(name = "NumberImplPort")
    public Numbers getNumberImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WS_Number/", "NumberImplPort"), Numbers.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NUMBERIMPLSERVICE_EXCEPTION!= null) {
            throw NUMBERIMPLSERVICE_EXCEPTION;
        }
        return NUMBERIMPLSERVICE_WSDL_LOCATION;
    }

}
