
package ws1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Numbers", targetNamespace = "http://WS_Number/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Numbers {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNumber", targetNamespace = "http://WS_Number/", className = "ws1.GetNumber")
    @ResponseWrapper(localName = "getNumberResponse", targetNamespace = "http://WS_Number/", className = "ws1.GetNumberResponse")
    @Action(input = "http://WS_Number/Numbers/getNumberRequest", output = "http://WS_Number/Numbers/getNumberResponse")
    public String getNumber();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "greatestNumber", targetNamespace = "http://WS_Number/", className = "ws1.GreatestNumber")
    @ResponseWrapper(localName = "greatestNumberResponse", targetNamespace = "http://WS_Number/", className = "ws1.GreatestNumberResponse")
    @Action(input = "http://WS_Number/Numbers/greatestNumberRequest", output = "http://WS_Number/Numbers/greatestNumberResponse")
    public void greatestNumber(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
